FROM golang:1.23-alpine AS builder

# Configuración del entorno
WORKDIR /app

COPY go.mod .
#COPY go.sum .

# Instalar dependencias
RUN go mod download

COPY . .

RUN go mod tidy

# Compilar
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/ap2 .
#Ahora se guarda nuestro archivo en la carpeta app con el nombre api

#este runtime se encarga de correr la aplicación,
#mientras que el otro se encarga de construir 
#runtime stage
FROM alpine:3.22

WORKDIR /app

COPY --from=builder /app/ap2 .

# Puerto expuesto (debe ser el mismo que el del servidor)
EXPOSE 8082

# Comando de ejecución
CMD ["./ap2"]