// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: weathertweet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WeatherTweetService_SendTweet_FullMethodName = "/weathertweet.WeatherTweetService/SendTweet"
)

// WeatherTweetServiceClient is the client API for WeatherTweetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio gRPC
type WeatherTweetServiceClient interface {
	SendTweet(ctx context.Context, in *WeatherTweetRequest, opts ...grpc.CallOption) (*WeatherTweetResponse, error)
}

type weatherTweetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeatherTweetServiceClient(cc grpc.ClientConnInterface) WeatherTweetServiceClient {
	return &weatherTweetServiceClient{cc}
}

func (c *weatherTweetServiceClient) SendTweet(ctx context.Context, in *WeatherTweetRequest, opts ...grpc.CallOption) (*WeatherTweetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WeatherTweetResponse)
	err := c.cc.Invoke(ctx, WeatherTweetService_SendTweet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeatherTweetServiceServer is the server API for WeatherTweetService service.
// All implementations must embed UnimplementedWeatherTweetServiceServer
// for forward compatibility.
//
// Servicio gRPC
type WeatherTweetServiceServer interface {
	SendTweet(context.Context, *WeatherTweetRequest) (*WeatherTweetResponse, error)
	mustEmbedUnimplementedWeatherTweetServiceServer()
}

// UnimplementedWeatherTweetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWeatherTweetServiceServer struct{}

func (UnimplementedWeatherTweetServiceServer) SendTweet(context.Context, *WeatherTweetRequest) (*WeatherTweetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTweet not implemented")
}
func (UnimplementedWeatherTweetServiceServer) mustEmbedUnimplementedWeatherTweetServiceServer() {}
func (UnimplementedWeatherTweetServiceServer) testEmbeddedByValue()                             {}

// UnsafeWeatherTweetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeatherTweetServiceServer will
// result in compilation errors.
type UnsafeWeatherTweetServiceServer interface {
	mustEmbedUnimplementedWeatherTweetServiceServer()
}

func RegisterWeatherTweetServiceServer(s grpc.ServiceRegistrar, srv WeatherTweetServiceServer) {
	// If the following call pancis, it indicates UnimplementedWeatherTweetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WeatherTweetService_ServiceDesc, srv)
}

func _WeatherTweetService_SendTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeatherTweetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherTweetServiceServer).SendTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherTweetService_SendTweet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherTweetServiceServer).SendTweet(ctx, req.(*WeatherTweetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WeatherTweetService_ServiceDesc is the grpc.ServiceDesc for WeatherTweetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeatherTweetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weathertweet.WeatherTweetService",
	HandlerType: (*WeatherTweetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTweet",
			Handler:    _WeatherTweetService_SendTweet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "weathertweet.proto",
}
